Add Review and Confirm feature to Payment Brick
lemazzo/sdk-react pull request #1
Opened 2023-09-25 19:51 UTC by lemazzo

Add Review and Confirm feature to Payment Brick

(Types descriptions will be in another PR to not delay this feature tests)

2023-09-25 20:33 UTC, AdaltonLeite approved these changes

2023-09-26 10:51 UTC, AleFossati requested changes

2023-09-26 10:51 UTC, AleFossati commented on src/bricks/payment/type.ts
> +  onRenderPreviousStep?: (param: string) => void;
```suggestion
  onRenderNextStep?: (currentStep: string) => void;
  onRenderPreviousStep?: (currentStep: string) => void;
```

2023-09-26 10:51 UTC, AleFossati commented on src/bricks/payment/type.ts
> +}
Já existe a `interface IAddress` que é quase igual a essa.
O que fizemos na lib de tipos que poderia ser feito aqui também, é mudar o nome desse `IReceiverAddress` para `IDefaultAddress`, por exemplo. E aí basta mudar a interface `IAddress` para ser assim:
```ts
interface IAddress extends Partial<IDefaultAddress> {
    // Partial é um helper do typescript que traz o outro tipo inteiro com todas as props opcionais.
    // A seguir, basta definir o `complement`, que é a única prop a mais que o IAddress possui.
    complement?: string;
}
```
Obs.: Manter os comentários do jsdoc que já existem.

2023-09-26 10:51 UTC, AleFossati commented on src/bricks/payment/type.ts
> +}
não precisamos criar essa nova interface, podemos usar a `interface IPayerIdentification` que já existe no `src/bricks/util/types/common.ts`

2023-09-26 10:51 UTC, AleFossati commented on src/bricks/payment/type.ts
> +}
essa interface é igual a `IReceiverAddress`, seria melhor usar a mesma pra evitar replicas

2023-09-26 11:08 UTC, AleFossati commented
Vou fazer uma lista aqui dos itens que eu também havia esquecido, mas o Isma e o Gui me lembraram na minha PR:

1. Adicionar nova prop css `secondaryColorListItem` nos **CustomVariables** do Payment.
2. Adicionar novas props do **AdditionalData**. Hoje só temos o `bin`, mas agora estamos devolvendo o `bin + lastFourDigits` para cartões salvos e `bin + lastFourDigits + cardholderName` para novos cartões.
3. Adicionar `additional_info` no formData do payment (na resposta do onSubmit).

Se quiser dar uma olhada no que já foi feito para a lib de tipos para adiantar, essas são as alterações: https://github.com/AleFossati/DefinitelyTyped/compare/DefinitelyTyped:DefinitelyTyped:master...master

2023-09-26 11:28 UTC, AleFossati commented
Acho que peguei um bug mais genérico que não tem a ver com a SDK-React, mas fazer um pagamento com Mercado Pago (wallet ou credits) tá redirecionando o buyer direto ao invés de abrir o Revisa e Confirma.

2023-09-26 11:40 UTC, lemazzo commented
> Acho que peguei um bug mais genérico que não tem a ver com a SDK-React, mas fazer um pagamento com Mercado Pago (wallet ou credits) tá redirecionando o buyer direto ao invés de abrir o Revisa e Confirma.

Valeu pelos comentários, Ale! Sobre esse ponto, o comportamento é esse mesmo. Não terá Revisa e Confirma para esses tipos de pagamento

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +      itemsList: [
Como não temos validação do nosso lado, acho importante criarmos exemplos onde todos os valores batem certinho da forma como deveria ser. Por exemplo, o valor do `amount` deveria ser a somatória dos valores dos items + shipping + discount. O `totalItemsAmount` também deveria representar o valor total dos `items`.

Acho que seria bacana inserir até um comentário acima desses valores, para deixar bem claro pro desenvolvedor.

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +          imageURL: 'http://www.mercadolivre.com',
Nenhuma das imagens estão aparecendo, pois a URL não termina com `.png .jpg` e etc.
Acho melhor colocarmos imagens que o integrador possa ver funcionando.

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +    },
Acho que seria melhor utilizarmos exemplos com nomes em inglês, a princípio nem vamos lançar no Brasil e se estiver em inglês pelo menos não precisamos adaptar depois pra espanhol.

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +      bankTransfer: ['pix'],
utilizar `bankTransfer: 'all'` para funcionar em todos os países.

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +    hideValuePropsFrom: [],
se não vamos esconder nada, acho melhor remover essa prop

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +  const onRenderPreviousStep = () => console.log('Calling onRenderNextStep...');
Adicionar o parâmetro para os integradores não se esquecerem
```suggestion
  const onRenderNextStep = (currentStep) => console.log('Calling onRenderNextStep...', currentStep);

  const onRenderPreviousStep = (currentStep) => console.log('Calling onRenderPreviousStep...', currentStep);
```

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/4-Simple-Review-Confirm.tsx
> +      bankTransfer: ['pix'],
`bankTransfer: 'all'`

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/4-Simple-Review-Confirm.tsx
> +    preferenceId: '1283129650-ea525882-af60-4895-b954-e8814a6c5b3c',
o get dessa preference está falhando

2023-09-26 11:59 UTC, AleFossati commented on examples/bricks/Payment/4-Simple-Review-Confirm.tsx
> +      totalItemsAmount: 331.14,
corrigir os `amounts`

2023-09-26 12:11 UTC, lemazzo commented on examples/bricks/Payment/4-Simple-Review-Confirm.tsx
> +      bankTransfer: ['pix'],
Tem algum bug na sdk que não está permitindo colocar "all" ou remover a prop bankTransfer. Se der tempo vejo ainda nessa PR, mas senão vou criar outra tarefa

2023-09-26 12:59 UTC, lemazzo commented on examples/bricks/Payment/3-Review-Confirm.tsx
> +      bankTransfer: ['pix'],
Tem algum bug na sdk que não está permitindo colocar "all" ou remover a prop bankTransfer. Se der tempo vejo ainda nessa PR, mas senão vou criar outra tarefa

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +    amount: 76.98, // result of = totalItemsAmount - costs (shipping) + totalDiscountsAmount
```suggestion
    amount: 76.98, // result of = totalItemsAmount + costs (shipping) - totalDiscountsAmount
```

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +        streetNumber: '5678',
```suggestion
        streetNumber: '<STREET_NUMBER>',
```

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +        streetNumber: '1234',
```suggestion
        streetNumber: '<STREET_NUMBER>',
```

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +    preferenceId: '',
remover preference vazia

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +      bankTransfer: ['pix'],
```suggestion
      bankTransfer: 'all',
```

2023-09-27 15:34 UTC, AleFossati commented on examples/bricks/Payment/3-Review-Confirm-Simple.tsx
> +      bankTransfer: ['pix'],
```suggestion
      bankTransfer: 'all',
```

2023-09-27 17:48 UTC, icaldana commented on examples/bricks/Payment/3-Review-Confirm-Simple.tsx
> +      bankTransfer: ['pix'],
ACHO que está assim por causa de uma tipagem incorreta que só aceita 'pix' nesse caso, embora podemos também já corrigir essa tipagem

2023-09-27 17:52 UTC, icaldana commented on src/bricks/payment/type.ts
> +  receiverAddress: IDefaultAddress;
Um detalhe chato de documentar é que `streetName`, `streetNumber` e `zipCode` são obrigatórios para o quadro de `IReviewConfirmShipping`, mas o objeto `IDefaultAddress` é compartilhado com mais de um fluxo, por exemplo `Payer`, que no caso os campos não são obrigatórios.

2023-09-27 17:52 UTC, icaldana commented on src/bricks/statusScreen/types.ts
> +export interface IStatusScreenBrickCustomVariables extends IBrickCustomVariables {
Valeu por exportar esses tipos!

2023-09-27 17:53 UTC, icaldana approved these changes
LGTM, comentários não bloqueantes.

2023-09-27 18:02 UTC, lemazzo commented on examples/bricks/Payment/3-Review-Confirm-Simple.tsx
> +      bankTransfer: ['pix'],
Ale me ajudou aqui a ver esse ponto. Deixamos de passar os valores através dessa variável customization e passamos a colocar direto, porque 'all' estava sendo interpretado pelo ts como string e não exatamente o valor 'all' como definido na tipagem AllOrArray

2023-09-27 18:12 UTC, lemazzo commented on src/bricks/payment/type.ts
> +  receiverAddress: IDefaultAddress;
`streetName`, `streetNumber` e `zipCode` são obrigatórios para qualquer uso de endereço. Então, se tiver um endereço, pelo menos esse 3 campos precisam receber informações e aí os campos opcionais que variam. Me pareceu que atende às necessidades, mas se percebeu algo faltando ou se não respondi bem, me dá um toque por favor :)

2023-09-27 18:13 UTC, lemazzo commented on examples/bricks/Payment/4-Review-Confirm-Full.tsx
> +      bankTransfer: ['pix'],
resolvido, obrigada pela ajuda!
Deixamos de passar os valores através dessa variável customization e passamos a colocar direto, porque 'all' estava sendo interpretado pelo ts como string e não exatamente o valor 'all' como definido na tipagem AllOrArray

2023-09-27 18:21 UTC, AleFossati commented on src/bricks/payment/type.ts
> +  receiverAddress: IDefaultAddress;
Me parece estar certo, porque o `Payer` da inicialização utiliza outro o `IAddress` e não `IDefaultAddress`.

2023-09-27 18:24 UTC, AleFossati approved these changes

2023-09-27 18:34 UTC, merged